### PR TITLE
make python script standalone

### LINKED ISSUE #12: [DEV] Allow per folder/file compilation from any working directory
**Is your feature request related to a problem? Please describe.**
1. Currently, scalu can only compile files explicitly put into the scalu_in folder, and only if the working directory is in `/python`. scalu should have the ability to compile folders/files from the command line without scalu_in.
2. scalu_out/scalu_in generation is relative to the actual working directory if outside the scalu project directory, which is bad.

**Describe the solution you'd like**
1. Implement an optional argument after the `compile` argument specifying the file or folder to be compiled. An additional optional argument should specify the relative path of scalu_out generation.
2. Check that this kind of relative folder generation doesn't happen unless specified.

### PR DESCRIPTION
**Pull request by getchoo**
this PR allows for `scalu.py` to be a standalone script by packaging it and its' associated libraries for pip, as well as accepting variable input and output folders/files when compiling. this would resolve #12

more details in commit messages

edit: never pushing a pr with github-cli again

### CODE REVIEW

**Comment by getchoo** [comment]
i consider this to be finished now. all of the expected builtin tests passed, along with some real world ones i did including:
- using `--output` as the only compile argument
- using `--input` as the only compile argument
- using both `--input` and `--output` as compile arguments
- mixing folders and directories with `--input`
- running the script inside of the project
- using the script in directories separate from the project's

adding packaging for pip also changes how the script would be run - so instead of using `python scalu.py` in the python folder,  `python -m scalu` would be used in the root of the project

the only thing i might want to add on is changing [this](https://github.com/ArgosOfIthica/scalu/blob/c1785857ddf45d771ae32ff5b0392796ae623699/python/src/cli/output_handling.py#L7) line in output_handling.py, as i think it could be useful to output files to directories without deleting any files or other child directories.

**Comment by ArgosOfIthica** [comment]
Great! I'll fully review this weekend.

**Comment by ArgosOfIthica** [comment]
Looks good.

https://github.com/ArgosOfIthica/scalu/pull/29/commits/36037d27050826a73a69a4ecc9394b9652b3ccd1

Hah, this reminded me why I never bothered doing this in the first place.

> the only thing i might want to add on is changing this line in output_handling.py

Yeah that's fine.

For documentation:

Can you update the readme to reflect how this changes the commands, as you've provided in the PR comments?

Can you provide examples of using --input/output?

Has the minimum Python version changed?

**Comment by getchoo** [comment]
> Can you update the readme to reflect how this changes the commands, as you've provided in the PR comments?
> Can you provide examples of using --input/output?
yep!

> Has the minimum Python version changed?
as far as i can tell, no - but i'll do some testing :)

**Comment by getchoo** [comment]
just installed python 3.6.8 and ran the regular tests and my own again, wasn't able to find any issues 👍🏻

**Pull request merged**
