### PR TITLE
WIP - Standard Library 

### PR DESCRIPTION
**Pull request by tmob03**
I'm not sure the best way of implementing this. What I have as of now is 70 KB compiled, don't want to add 70 KB to every script that uses this. Maybe along with #22 a #INCLUDE preprocessor directive, but it detects whether some service is being used or not, and removes it's `map` entry, as they are only there as of now so all the services don't get optimized away by the compiler. 

PRNG and bitshifts taken from the already existing examples.

Note: Due to compiler limitations of not allowing quotes in source calls, the space character and semicolon cannot properly compile in in the `coutchar`  service and must be hand edited in the compiled script. The open and close brackets suffer from a similar issue, but because the compiler thinks the source call is ending or a new one is starting.

### CODE REVIEW

**Comment by tmob03** [comment]
Actually I’m dumb. I can just remove all the map binds except boot, and if it’s #INCLUDEd the normal way, the compiler would optimize away the unused services.

**Comment by tmob03** [comment]
I want to create a console input service but I'm not sure how without creating a long list of each char and int in a map bind. If I did this it would make these services go into each script utilizing the library, any ideas?

**Comment by ArgosOfIthica** [comment]
> Note: Due to compiler limitations of not allowing quotes in source calls, the space character and semicolon cannot properly compile in in the `coutchar` service and must be hand edited in the compiled script. The open and close brackets suffer from a similar issue, but because the compiler thinks the source call is ending or a new one is starting.

I am unaware of a way to print `;` and `"` specifically via aliases without just executing a cfg file. If there's a way to do this, show me and we can work to amend how that works.

For `]`, we can make a simple escape character to pair with it. If you're interested in Python development, this may be a good first issue; I don't care about escaping the escape sequence or anything like that.

> I want to create a console input service but I'm not sure how without creating a long list of each char and int in a map bind. If I did this it would make these services go into each script utilizing the library, any ideas?

I'm not quite sure what this is. You'll have to elaborate on the intent.


As for the greater library, it's looking good. For the multiplication and division algorithms that involve recursion, it's very important they terminate for all inputs or else we will hang the engine. For division by zero, it is acceptable to return a false answer and maybe do something else, like set a division by zero flag.

**Comment by tmob03** [comment]
> I am unaware of a way to print ; and " specifically via aliases without just executing a cfg file. If there's a way to do this, show me and we can work to amend how that works.

Oh I see. I forget everything is enclosed in aliases, I only tested for how to echo these characters in game, and assumed changing the outputted cfg file would work. I still think they should be included so the input number aligns with the ASCII standard, minus unprintable characters of course.

> For ], we can make a simple escape character to pair with it. If you're interested in Python development, this may be a good first issue; I don't care about escaping the escape sequence or anything like that.

Unfortunately I'm not really a programmer, I only know the basic syntax of JS and C++, but not enough to really apply it at the moment.

> I'm not quite sure what this is. You'll have to elaborate on the intent.

As with your hangman game, you created a console input through a map bind ie map { a: @a} etc. I want to include something like this as well, but I'm not sure how to create an input like that without using a map bind, as if I did it would get included into any script using this library whether it used it or not.

**Comment by tmob03** [comment]
I don't know what more to add at the moment because map blocks will always include the services in the compiled file, whether they are used or not, see above comment. If you have any more things I should add let me know

**Comment by ArgosOfIthica** [comment]
I definitely want to add more onto this, but for now I'm going to go ahead and add this in.

**Pull request merged**
